### ISSUE TITLE
Feature : Explain 'Done' better

### ISSUE THREAD

**Issue by glennsarti** [denysdovhan/inboxer#12]
~~The web based gmail client has dedicated buttons to archive emails.
Inboxer doesn't seem to have this facility, or this facility exists but under a different name.~~

It appears the concept of 'Done' is means it appears in the archive folder but there's no way I could be 100% sure.

The concept of 'Done' doesn't appear to exist in the Gmail web client so this is something new for users coming from web to Inboxer.  This could do with more explanation.   Perhaps as simple as modifying the tooltip so when you hover the mouse over the "Done" button highlight that this would archive it.

**Comment by federomano** [comment]
This is no bug nor feature, **Done** is an Inbox concept, similar to **Archive** in Gmail but with a different approach. You're having the issue because you're moving from Gmail to Inbox, not because you're moving from Gmail to Inboxer. For help on the meaning and usage of **Done**, chech Inbox's help: https://support.google.com/inbox/answer/6067561

**Comment by glennsarti** [comment]
Ahh ok...That's what I was missing.  Thank for you explaining that.
