### ISSUE TITLE
Feature : Suppress notifications on first time on usage

### ISSUE THREAD

**Issue by glennsarti** [denysdovhan/inboxer#13]
Actual Behaviour:
When I first installed and configured Inboxer it started popping up notifications for every single email in my inbox, once per second.

This was a really annoying experience as a first time user. Also I couldn't find anything in settings to suppress notifications temporarily (Apart from suppressing all notifications in Windows)

Expected Behaviour:
- Inboxer should only start notifying me of new emails, not emails that already exist in my inbox
- Ideally, should be able to suppress notifications for a short time frame

Environment - Windows 10

**Comment by denysdovhan** [comment]
Hmmm. This bug was present before but now it's should be fixed. Maybe binaries aren't recompiled from the latest version of source code. Let me take a look.

**Comment by schuylermk** [comment]
I have an issue that I believe is in the same vein. After first installation and opening, I'm getting popups for the same new email from yesterday (or the day before) over and over. 
Also, even worse, I attempted to make it go away/turn it off in the *preferences and now get this alert that can't be done away with:
> Uncaught Exception:
TypeError: Error processing argument at index 0, conversion failure from undefined
    at EventEmitter.ipcMain.on (/Applications/Inboxer.app/Contents/Resources/app.asar/app/main/index.js:155:9)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:194:7)
    at WebContents.<anonymous> (/Applications/Inboxer.app/Contents/Resources/electron.asar/browser/api/web-contents.js:247:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:194:7)

*however, I can't remember the name of the preference/toggle because I can't access it due to the continual alert/popup.

**Comment by jmarino** [comment]
Closing bug from very old version. Please reopen if issue still persists with latest version.
