### ISSUE TITLE
Re-merge top navbar

### ISSUE THREAD

**Issue by madeleineostoja** [denysdovhan/inboxer#71]
Latest update split the window chrome from the top navbar of Inbox, and now the app literally looks like Inbox is shoved into an Electron window – was there a reason for the UI regression?

<img width="385" alt="screen shot 2018-09-10 at 11 29 14 am" src="https://user-images.githubusercontent.com/6374876/45292355-deeaa000-b4ec-11e8-8eee-c1026ae50d8b.png">

**Comment by aarondemolder** [comment]
I've just started using Inboxer on windows 10 and noticed this is split by default.
I guess this could be changed alongside a correction for above?
Does this help? - https://github.com/sidneys/electron-titlebar-windows
(I've never used electron otherwise would try to make a PR)

Edit: Might learn how to use electron to implement this myself

**Comment by denysdovhan** [comment]
I want to close this project. Take a look at the explanation: #101

If you still need this project, please, fork the repo.
