### ISSUE TITLE
Looks nothing like Google Inbox?

### ISSUE THREAD

**Issue by trekze** [denysdovhan/inboxer#95]
I'm a little confused. Is this not supposed to make your gmail look and function more like inbox? I downloaded the source, npm install/start and I get an electron app that just looks like a wrapper around the regular gmail.

There is no Google Inbox UI in sight.

**Comment by jmarino** [comment]
This is my fault, let me explain. Inboxer worked by packaging the Inbox web-version as a desktop app. However, Google [decided to discontinue](https://www.blog.google/products/gmail/inbox-signing-find-your-favorite-features-new-gmail/) Inbox by the end of March leaving us in a pickle. Either we accept that Inboxer will stop working at the end of the month or we attempt to implement all of Inbox features on top of regular Gmail. For now we have reworked Inboxer to work with regular gmail so that Inboxer will continue to work beyond this month.

I did not think about how confusing this sudden change would be, with a new release that simply shows gmail. This whole thing could have been done much better. I think it would make sense to have a dialog window that displays on 1st run explaining the situation, and maybe a more detailed explanation in the README file.

**Comment by jmarino** [comment]
There's a new release (v1.3.1) that provides some info to the user on startup in the hopes of reducing the confusion this whole situation is creating. Nothing else is changed though, it still uses regular Gmail.

If you want to keep using Inboxer with Inbox you can use release v1.2.2, which is still based on Inbox. Be warned, that version will most likely stop working once Google pulls the plug on Inbox.

**Comment by trekze** [comment]
Cool. I just brought it up because this project has been referenced on Reddit as an alternative to inbox, once inbox is gone, which it obviously isn't as it relies on Inbox to provide the Inbox experience. Perhaps one day! Keep up the good work.

**Comment by E14** [comment]
@jmarino is there a branch going for an inbox-on-top-of-gmail implementation?

**Comment by jmarino** [comment]
We don't have anything towards an implementation of Inbox on top of Gmail at this point. And let me be honest, it sounds like a really difficult task that may not be worth the trouble. Google does not expose their API to access email, we are left with the final html product that Gmail/Inbox produces. Inboxer parses it to detect new messages and such.

In my mind to re-implement Inbox on top of Gmail we would have to parse email messages from Gmail and repackage them to make them look as Inbox. Have a background Gmail page from where we mine the data and a user facing one where we show an Inbox like view. This sounds like a nightmare but I would love to be proved wrong :P

I am sad that Inbox is going away, it was a really interesting interface for email. But I still see value in Inboxer working with Gmail, I like having a stand alone email client rather than a browser tab. So even if I'm forced to use Gmail and not Inbox, it's still preferable to do it though Inboxer than through imap and a regular email client.

**Comment by E14** [comment]
I see, I kinda expected Google to have implemented a proper API, but probably it exist, and it's just not being used/accessible by the web interface but only the mobile apps

**Comment by trekze** [comment]
@E14 It would be interesting to reverse-engineer the  API that the mobile app uses, but there's a good chance they're going to turn that off anyway when they turn off Inbox, so it might be in vain.

**Comment by vutsalsinghal** [comment]
Can we do something like [sortd](https://www.sortd.com) but instead have inbox by Gmail UI/UX?

**Comment by trekze** [comment]
Best alternative I’ve found is Edison mail. But it’s an app for iOS. No desktop/web version.

**Comment by mikewse** [comment]
With the recent switch back to the classic Gmail UI it would make sense to rename the project Gmailer instead of Inboxer.
I think as long as it is called Inboxer people will expect the Inbox by Gmail UI experience. I'm one of them. By chance I found this issue otherwise I would not have known until downloading and installing which would have felt lame...

**Comment by trekze** [comment]
At the very least the readme needs to be modified. THere’s still a screenshot that shows inbox.

**Comment by jmarino** [comment]
A new screenshot would be a great and fairly easy contribution to the project.

**Comment by denysdovhan** [comment]
I want to close this project. Take a look at the explanation: https://github.com/denysdovhan/inboxer/issues/101

If you still need this project, please, fork the repo.
