### ISSUE TITLE
Web version?

### ISSUE THREAD

**Issue by devcastoro** [denysdovhan/inboxer#98]
Do you thought about a web version? If yes, I would like to help on that

**Comment by jmarino** [comment]
What exactly do you mean by a web version? 
Inboxer packages Inbox/Gmail as a desktop electron app, it is already using the web version of Inbox/Gmail.

**Comment by devcastoro** [comment]
A website where you can use Inbox as a Web app: https://inbox.google.com

**Comment by jmarino** [comment]
Like a said, Inboxer is already doing exactly that.
Take a look at `app/main/index.js` from the `inbox` branch:

line 21: `const mainURL = 'https://inbox.google.com/';`

line 109:  `win.loadURL(mainURL);`

**Comment by vutsalsinghal** [comment]
I think what @devcastoro meant was to have "inboxer" website which modifies the gmail UI to that of inbox UI...

**Comment by devcastoro** [comment]
I mean a standalone website which you can use from every platform (not only on the platform where you had installed the Inboxer app)

**Comment by jmarino** [comment]
I'm afraid that's out of the scope of Inboxer. It would bring things back into the browser, while the main purpose of Inboxer was to provide Inbox as a desktop app.
However, it would technically be very similar to what we do now. After all, we use electron to render html and interact with the javascript. In a re-implementation of Inbox with electron, the final _web page_ would be locally produced and displayed with electron instead of being hosted externally.

There's been some talk about re-implementing Inbox on top of Gmail (see #77 and #95). The main problem is that Gmail does not expose its email API, we only have access to the final html. One way forward would require a background process to access Gmail to mine the data and a front facing one that re-renders it to simulate Inbox. It sounds very complicated, there would need to be a translation layer to transfer actions back and forth between the front interface and background Gmail with many possibilities for things to go wrong and get out of sync.
Another thing people have suggested is to use a [Gmail add-on](https://developers.google.com/gsuite/add-ons/overview). I have not looked into how difficult/practical this is.

Don't let me discourage you, though. Your offer of help is very welcome and even though we don't have a clear way forward yet, there is a lot of interest in reviving an Inbox like interface.

**Comment by devcastoro** [comment]
Hi @jmarino, thank you for this very deepen answer. 

I've understood how Inboxer works and it seems perfect if you want to use the old "Inbox By Gmail" interface on a Mac/Windows. But what about mobile users and who don't want to install an email client? 

[I haven't deepened these Gmail API](https://developers.google.com/gmail/api/v1/reference/users/messages/send), but from what I've seen, seems that these API give you access to every Gmail feature. I'm wrong?

**Comment by jmarino** [comment]
That is very interesting @devcastoro! I was not aware of this Gmail API. Could we convince you to help us implement this API in Inboxer?

About mobile, do you know if electron apps can run on Android/iOS?

**Comment by devcastoro** [comment]
> That is very interesting @devcastoro! I was not aware of this Gmail API. Could we convince you to help us implement this API in Inboxer?
> 
> About mobile, do you know if electron apps can run on Android/iOS?

@jmarino  Is what I'm searching for! But, instead of implementing those API in an electron app, I would prefer to develop a Web backend with Symfony (Php) with a ReactJS frontend for web and React-Native (or Electron... Why not) for mobile.

Is this the right place for this project?

**Comment by jmarino** [comment]
Full disclosure: I am not the owner of this repo. But from my point of view I would say this is not the right place for your idea. I would suggest that you should start a new project.

I hope there will be room for cooperation between both projects down the line, since we're aiming at the same thing. Best of luck.

**Comment by devcastoro** [comment]
> Full disclosure: I am not the owner of this repo. But from my point of view I would say this is not the right place for your idea. I would suggest that you should start a new project.
> 
> I hope there will be room for cooperation between both projects down the line, since we're aiming at the same thing. Best of luck.

Thank you for your suggestions and for the possible support :D

**Comment by denysdovhan** [comment]
I want to close this project. Take a look at the explanation: https://github.com/denysdovhan/inboxer/issues/101

If you still need this project, please, fork the repo.
